// <auto-generated />
namespace pAPP_Palindrome.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Create_PalindromeStrings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_PalindromeStrings));
        
        string IMigrationMetadata.Id
        {
            get { return "201802180506004_Create_PalindromeStrings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
